.TH "C:/Users/Diogo/Desktop/Trab_Pratico_POO_LESI_Fase3_26534_26006/Projeto_POO/DLLs/ObjetosNegocio Directory Reference" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Diogo/Desktop/Trab_Pratico_POO_LESI_Fase3_26534_26006/Projeto_POO/DLLs/ObjetosNegocio Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCarrinhoCompra\&.cs\fP"
.br
.ti -1c
.RI "file \fBCategoria\&.cs\fP"
.br
.ti -1c
.RI "file \fBCompra\&.cs\fP"
.br
.ti -1c
.RI "file \fBFornecedor\&.cs\fP"
.br
.ti -1c
.RI "file \fBICarrinhoCompra\&.cs\fP"
.br
.ti -1c
.RI "file \fBICategoria\&.cs\fP"
.br
.ti -1c
.RI "file \fBIFornecedor\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMarca\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMorada\&.cs\fP"
.br
.ti -1c
.RI "file \fBIOperacao\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPessoa\&.cs\fP"
.br
.ti -1c
.RI "file \fBIProduto\&.cs\fP"
.br
.ti -1c
.RI "file \fBIUtilizador\&.cs\fP"
.br
.ti -1c
.RI "file \fBMarca\&.cs\fP"
.br
.ti -1c
.RI "file \fBMorada\&.cs\fP"
.br
.ti -1c
.RI "file \fBOperacao\&.cs\fP"
.br
.ti -1c
.RI "file \fBPessoa\&.cs\fP"
.br
.ti -1c
.RI "file \fBProduto\&.cs\fP"
.br
.ti -1c
.RI "file \fBUtilizador\&.cs\fP"
.br
.ti -1c
.RI "file \fBVenda\&.cs\fP"
.br
.in -1c
