.TH "Dados" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dados
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArmazem\fP"
.br
.RI "Purpose: Created by: Diogo Created on: 06/12/2023 23:09:36\&. "
.ti -1c
.RI "class \fBCompras\fP"
.br
.RI "Purpose: Compras de classe Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBFornecedores\fP"
.br
.RI "Purpose: Fornecedores de classe Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBUtilizadores\fP"
.br
.RI "Purpose: Classe de utilizadores Created by: Diogo Created on: 06/12/2023 23:09:52\&. "
.ti -1c
.RI "class \fBVendas\fP"
.br
.RI "Purpose: Vendas de classe Created by: Diogo Created on: 24/10/2023\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
