.TH "Excecoes.ArmazemExcecoes" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Excecoes.ArmazemExcecoes \- Purpose: Classe de exceções de armazem Created by: Diogo Created on: 06/12/2023 22:34:55\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArmazemExcecoes\fP (string mensagem)"
.br
.ti -1c
.RI "\fBArmazemExcecoes\fP ()"
.br
.ti -1c
.RI "\fBArmazemExcecoes\fP (string mensagem, Exception e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Classe de exceções de armazem Created by: Diogo Created on: 06/12/2023 22:34:55\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Excecoes\&.ArmazemExcecoes\&.ArmazemExcecoes (string mensagem)"

.SS "Excecoes\&.ArmazemExcecoes\&.ArmazemExcecoes ()"

.SS "Excecoes\&.ArmazemExcecoes\&.ArmazemExcecoes (string mensagem, Exception e)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
