.TH "Excecoes.VendasExcecoes" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Excecoes.VendasExcecoes \- Purpose: Classe de venda de exceções Created by: Diogo Created on: 24/10/2023\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVendasExcecoes\fP (string mensagem)"
.br
.ti -1c
.RI "\fBVendasExcecoes\fP ()"
.br
.ti -1c
.RI "\fBVendasExcecoes\fP (string mensagem, Exception e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Classe de venda de exceções Created by: Diogo Created on: 24/10/2023\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Excecoes\&.VendasExcecoes\&.VendasExcecoes (string mensagem)"

.SS "Excecoes\&.VendasExcecoes\&.VendasExcecoes ()"

.SS "Excecoes\&.VendasExcecoes\&.VendasExcecoes (string mensagem, Exception e)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
