.TH "Excecoes" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Excecoes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArmazemExcecoes\fP"
.br
.RI "Purpose: Classe de exceções de armazem Created by: Diogo Created on: 06/12/2023 22:34:55\&. "
.ti -1c
.RI "class \fBCarrinhoCompraExcecoes\fP"
.br
.RI "Purpose: Classe de exceções de carrinho de compra Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBComprasExcecoes\fP"
.br
.RI "Purpose: ComprasExcecoes de classe Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBFornecedoresExcecoes\fP"
.br
.RI "Purpose: Classe de exceções de fornecedores Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBProdutoExcecoes\fP"
.br
.RI "Purpose: Classe de exceções de produto Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBUtilizadoresExcecoes\fP"
.br
.RI "Purpose: Classe de exceções de utilizadores Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBVendasExcecoes\fP"
.br
.RI "Purpose: Classe de venda de exceções Created by: Diogo Created on: 24/10/2023\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
