.TH "Excecoes.CarrinhoCompraExcecoes" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Excecoes.CarrinhoCompraExcecoes \- Purpose: Classe de exceções de carrinho de compra Created by: Diogo Created on: 24/10/2023\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCarrinhoCompraExcecoes\fP (string mensagem)"
.br
.ti -1c
.RI "\fBCarrinhoCompraExcecoes\fP ()"
.br
.ti -1c
.RI "\fBCarrinhoCompraExcecoes\fP (string mensagem, Exception e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Classe de exceções de carrinho de compra Created by: Diogo Created on: 24/10/2023\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Excecoes\&.CarrinhoCompraExcecoes\&.CarrinhoCompraExcecoes (string mensagem)"

.SS "Excecoes\&.CarrinhoCompraExcecoes\&.CarrinhoCompraExcecoes ()"

.SS "Excecoes\&.CarrinhoCompraExcecoes\&.CarrinhoCompraExcecoes (string mensagem, Exception e)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
