.TH "ObjetosNegocio" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCarrinhoCompra\fP"
.br
.RI "Purpose: Classe de carrinho de compra Created by: Diogo Created on: 07/12/2023 21:21:00\&. "
.ti -1c
.RI "class \fBCategoria\fP"
.br
.RI "Purpose: Classe de categoria Created by: Diogo Created on: 06/12/2023 23:02:38\&. "
.ti -1c
.RI "class \fBCompra\fP"
.br
.RI "Purpose: Compra de classe Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBFornecedor\fP"
.br
.RI "Purpose: Classe de fornecedor Created by: Diogo Created on: 06/12/2023 23:35:37\&. "
.ti -1c
.RI "interface \fBICarrinhoCompra\fP"
.br
.RI "Purpose: Created by: Diogo Created on: 20/12/2023 03:40:49\&. "
.ti -1c
.RI "interface \fBICategoria\fP"
.br
.RI "Purpose: Interface de categoria Created by: Diogo Created on: 20/12/2023 03:20:54\&. "
.ti -1c
.RI "interface \fBIFornecedor\fP"
.br
.RI "Purpose: Interface de fornecedor Created by: Diogo Created on: 20/12/2023 03:32:38\&. "
.ti -1c
.RI "interface \fBIMarca\fP"
.br
.RI "Purpose: Interface de marca Created by: Diogo Created on: 20/12/2023 03:25:35\&. "
.ti -1c
.RI "interface \fBIMorada\fP"
.br
.RI "Purpose: Interface de morada Created by: Diogo Created on: 20/12/2023 03:28:55\&. "
.ti -1c
.RI "interface \fBIOperacao\fP"
.br
.RI "Purpose: Created by: Diogo Created on: 29/12/2023 21:17:59\&. "
.ti -1c
.RI "interface \fBIPessoa\fP"
.br
.RI "Purpose: Interface de pessoa Created by: Diogo Created on: 20/12/2023 03:35:05\&. "
.ti -1c
.RI "interface \fBIProduto\fP"
.br
.RI "Purpose: Interface de produto Created by: Diogo Created on: 20/12/2023 03:37:11\&. "
.ti -1c
.RI "interface \fBIUtilizador\fP"
.br
.RI "Purpose: Created by: Diogo Created on: 20/12/2023 03:40:31\&. "
.ti -1c
.RI "class \fBMarca\fP"
.br
.RI "Purpose: Classe de marca Created by: Diogo Created on: 06/12/2023 23:03:12\&. "
.ti -1c
.RI "class \fBMorada\fP"
.br
.RI "Purpose: Classe de morada Created by: Diogo Created on: 06/12/2023 23:01:07\&. "
.ti -1c
.RI "class \fBOperacao\fP"
.br
.RI "Purpose: Created by: Diogo Created on: 29/12/2023 21:20:29\&. "
.ti -1c
.RI "class \fBPessoa\fP"
.br
.RI "Purpose: Classe de Pessoa Created by: Diogo Created on: 06/12/2023 23:00:29\&. "
.ti -1c
.RI "class \fBProduto\fP"
.br
.RI "Purpose: Classe de Produto Created by: Diogo Created on: 06/12/2023 23:11:28\&. "
.ti -1c
.RI "class \fBUtilizador\fP"
.br
.RI "Purpose: Classe de utilizador Created by: Diogo Created on: 06/12/2023 23:04:52\&. "
.ti -1c
.RI "class \fBVenda\fP"
.br
.RI "Purpose: Venda de classe Created by: Diogo Created on: 24/10/2023\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
