.TH "ObjetosNegocio.IMorada" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.IMorada \- Purpose: Interface de morada Created by: Diogo Created on: 20/12/2023 03:28:55\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.Morada\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCidade\fP\fC [get, set]\fP"
.br
.RI "Propriedade para cidade\&. "
.ti -1c
.RI "string \fBDistrito\fP\fC [get, set]\fP"
.br
.RI "Propriedade para distrito\&. "
.ti -1c
.RI "string \fBRua\fP\fC [get, set]\fP"
.br
.RI "Propriedade para rua\&. "
.ti -1c
.RI "int \fBNumPorta\fP\fC [get, set]\fP"
.br
.RI "Propriedade para numero de porta\&. "
.ti -1c
.RI "string \fBCodigoPostal\fP\fC [get, set]\fP"
.br
.RI "Propriedade para codigo postal\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Interface de morada Created by: Diogo Created on: 20/12/2023 03:28:55\&. 


.SH "Property Documentation"
.PP 
.SS "string ObjetosNegocio\&.IMorada\&.Cidade\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para cidade\&. 
.PP
Implemented in \fBObjetosNegocio\&.Morada\fP\&.
.SS "string ObjetosNegocio\&.IMorada\&.CodigoPostal\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para codigo postal\&. 
.PP
Implemented in \fBObjetosNegocio\&.Morada\fP\&.
.SS "string ObjetosNegocio\&.IMorada\&.Distrito\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para distrito\&. 
.PP
Implemented in \fBObjetosNegocio\&.Morada\fP\&.
.SS "int ObjetosNegocio\&.IMorada\&.NumPorta\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para numero de porta\&. 
.PP
Implemented in \fBObjetosNegocio\&.Morada\fP\&.
.SS "string ObjetosNegocio\&.IMorada\&.Rua\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para rua\&. 
.PP
Implemented in \fBObjetosNegocio\&.Morada\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
