.TH "ObjetosNegocio.IProduto" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.IProduto \- Purpose: Interface de produto Created by: Diogo Created on: 20/12/2023 03:37:11\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.Produto\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBRefProd\fP\fC [get, set]\fP"
.br
.RI "Propriedade para referencia de produto\&. "
.ti -1c
.RI "int \fBQuantidade\fP\fC [get, set]\fP"
.br
.RI "Propriedade para quantidade do produto\&. "
.ti -1c
.RI "string \fBNome\fP\fC [get, set]\fP"
.br
.RI "Propriedade para nome\&. "
.ti -1c
.RI "double \fBPreco\fP\fC [get, set]\fP"
.br
.RI "Propriedade para preco\&. "
.ti -1c
.RI "\fBCategoria\fP \fBCat\fP\fC [get, set]\fP"
.br
.RI "Propriedade para categoria do produto\&. "
.ti -1c
.RI "\fBMarca\fP \fBMar\fP\fC [get, set]\fP"
.br
.RI "Propriedade para marca do produto\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Interface de produto Created by: Diogo Created on: 20/12/2023 03:37:11\&. 


.SH "Property Documentation"
.PP 
.SS "\fBCategoria\fP ObjetosNegocio\&.IProduto\&.Cat\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para categoria do produto\&. 
.PP
Implemented in \fBObjetosNegocio\&.Produto\fP\&.
.SS "\fBMarca\fP ObjetosNegocio\&.IProduto\&.Mar\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para marca do produto\&. 
.PP
Implemented in \fBObjetosNegocio\&.Produto\fP\&.
.SS "string ObjetosNegocio\&.IProduto\&.Nome\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para nome\&. 
.PP
Implemented in \fBObjetosNegocio\&.Produto\fP\&.
.SS "double ObjetosNegocio\&.IProduto\&.Preco\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para preco\&. 
.PP
Implemented in \fBObjetosNegocio\&.Produto\fP\&.
.SS "int ObjetosNegocio\&.IProduto\&.Quantidade\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para quantidade do produto\&. 
.PP
Implemented in \fBObjetosNegocio\&.Produto\fP\&.
.SS "int ObjetosNegocio\&.IProduto\&.RefProd\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para referencia de produto\&. 
.PP
Implemented in \fBObjetosNegocio\&.Produto\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
