.TH "ObjetosNegocio.IUtilizador" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.IUtilizador \- Purpose: Created by: Diogo Created on: 20/12/2023 03:40:31\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.Utilizador\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBEmail\fP\fC [get, set]\fP"
.br
.RI "Propriedade para email\&. "
.ti -1c
.RI "string \fBPassword\fP\fC [get, set]\fP"
.br
.RI "Propriedade para password\&. "
.ti -1c
.RI "\fBCarrinhoCompra\fP \fBCarrinho\fP\fC [get, set]\fP"
.br
.RI "Propriedade para carrinho de compras\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Created by: Diogo Created on: 20/12/2023 03:40:31\&. 


.SH "Property Documentation"
.PP 
.SS "\fBCarrinhoCompra\fP ObjetosNegocio\&.IUtilizador\&.Carrinho\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para carrinho de compras\&. 
.PP
Implemented in \fBObjetosNegocio\&.Utilizador\fP\&.
.SS "string ObjetosNegocio\&.IUtilizador\&.Email\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para email\&. 
.PP
Implemented in \fBObjetosNegocio\&.Utilizador\fP\&.
.SS "string ObjetosNegocio\&.IUtilizador\&.Password\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para password\&. 
.PP
Implemented in \fBObjetosNegocio\&.Utilizador\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
