.TH "ObjetosNegocio.Morada" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.Morada \- Purpose: Classe de morada Created by: Diogo Created on: 06/12/2023 23:01:07\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjetosNegocio\&.IMorada\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMorada\fP ()"
.br
.RI "Construtor de classe por defeito\&. "
.ti -1c
.RI "\fBMorada\fP (string cidade, string distrito, string rua, string codigoPostal, int numPorta)"
.br
.RI "Construtor de classe com os atributos declarados\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Devolve uma string com todas as propriedades de uma morada\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.RI "Compara a igualdade de dois objetos\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator==\fP (\fBMorada\fP m1, \fBMorada\fP m2)"
.br
.RI "Compara a igualdade de duas moradas através dos seus parâmetros\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBMorada\fP m1, \fBMorada\fP m2)"
.br
.RI "Compara a diferenciabilidade de duas moradas através dos seus parâmetros\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCidade\fP\fC [get, set]\fP"
.br
.RI "Propriedade para cidade\&. "
.ti -1c
.RI "string \fBDistrito\fP\fC [get, set]\fP"
.br
.RI "Propriedade para distrito\&. "
.ti -1c
.RI "string \fBRua\fP\fC [get, set]\fP"
.br
.RI "Propriedade para rua\&. "
.ti -1c
.RI "int \fBNumPorta\fP\fC [get, set]\fP"
.br
.RI "Propriedade para numero de porta\&. "
.ti -1c
.RI "string \fBCodigoPostal\fP\fC [get, set]\fP"
.br
.RI "Propriedade para codigo postal\&. "
.in -1c

Properties inherited from \fBObjetosNegocio\&.IMorada\fP
.in +1c
.ti -1c
.RI "string \fBCidade\fP\fC [get, set]\fP"
.br
.RI "Propriedade para cidade\&. "
.ti -1c
.RI "string \fBDistrito\fP\fC [get, set]\fP"
.br
.RI "Propriedade para distrito\&. "
.ti -1c
.RI "string \fBRua\fP\fC [get, set]\fP"
.br
.RI "Propriedade para rua\&. "
.ti -1c
.RI "int \fBNumPorta\fP\fC [get, set]\fP"
.br
.RI "Propriedade para numero de porta\&. "
.ti -1c
.RI "string \fBCodigoPostal\fP\fC [get, set]\fP"
.br
.RI "Propriedade para codigo postal\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Classe de morada Created by: Diogo Created on: 06/12/2023 23:01:07\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ObjetosNegocio\&.Morada\&.Morada ()"

.PP
Construtor de classe por defeito\&. 
.SS "ObjetosNegocio\&.Morada\&.Morada (string cidade, string distrito, string rua, string codigoPostal, int numPorta)"

.PP
Construtor de classe com os atributos declarados\&. 
.PP
\fBParameters\fP
.RS 4
\fIcidade\fP cidade
.br
\fIdistrito\fP distrito
.br
\fIrua\fP rua
.br
\fIcodigoPostal\fP codigo postal
.br
\fInumPorta\fP numero da porta
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override bool ObjetosNegocio\&.Morada\&.Equals (object obj)"

.PP
Compara a igualdade de dois objetos\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP objeto
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se for igual ou não
.RE
.PP

.SS "static bool ObjetosNegocio\&.Morada\&.operator!= (\fBMorada\fP m1, \fBMorada\fP m2)\fC [static]\fP"

.PP
Compara a diferenciabilidade de duas moradas através dos seus parâmetros\&. 
.PP
\fBParameters\fP
.RS 4
\fIm1\fP morada 1
.br
\fIm2\fP morada 2
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se for diferente ou não
.RE
.PP

.SS "static bool ObjetosNegocio\&.Morada\&.operator== (\fBMorada\fP m1, \fBMorada\fP m2)\fC [static]\fP"

.PP
Compara a igualdade de duas moradas através dos seus parâmetros\&. 
.PP
\fBParameters\fP
.RS 4
\fIm1\fP morada 1
.br
\fIm2\fP morada 2
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se for igual ou não
.RE
.PP

.SS "override string ObjetosNegocio\&.Morada\&.ToString ()"

.PP
Devolve uma string com todas as propriedades de uma morada\&. 
.PP
\fBReturns\fP
.RS 4
string final
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string ObjetosNegocio\&.Morada\&.Cidade\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para cidade\&. 
.PP
Implements \fBObjetosNegocio\&.IMorada\fP\&.
.SS "string ObjetosNegocio\&.Morada\&.CodigoPostal\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para codigo postal\&. 
.PP
Implements \fBObjetosNegocio\&.IMorada\fP\&.
.SS "string ObjetosNegocio\&.Morada\&.Distrito\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para distrito\&. 
.PP
Implements \fBObjetosNegocio\&.IMorada\fP\&.
.SS "int ObjetosNegocio\&.Morada\&.NumPorta\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para numero de porta\&. 
.PP
Implements \fBObjetosNegocio\&.IMorada\fP\&.
.SS "string ObjetosNegocio\&.Morada\&.Rua\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para rua\&. 
.PP
Implements \fBObjetosNegocio\&.IMorada\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
