.TH "ObjetosNegocio.Operacao" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.Operacao \- Purpose: Created by: Diogo Created on: 29/12/2023 21:20:29\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjetosNegocio\&.IOperacao\fP\&.
.PP
Inherited by \fBObjetosNegocio\&.Compra\fP, and \fBObjetosNegocio\&.Venda\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOperacao\fP ()"
.br
.RI "Construtor de classe por defeito\&. "
.ti -1c
.RI "\fBOperacao\fP (Dictionary< int, int > prods, string username, DateTime dataOp)"
.br
.RI "Construtor de classe com os parâmetros definidos\&. "
.ti -1c
.RI "abstract bool \fBEmitirFatura\fP ()"
.br
.RI "Emite uma fatura\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBDataOp\fP\fC [get, set]\fP"
.br
.RI "Propriedade para data de venda\&. "
.ti -1c
.RI "string \fBUsername\fP\fC [get, set]\fP"
.br
.RI "Propriedade para username\&. "
.ti -1c
.RI "Dictionary< int, int > \fBProds\fP\fC [get, set]\fP"
.br
.RI "Propriedade para produtos\&. "
.in -1c

Properties inherited from \fBObjetosNegocio\&.IOperacao\fP
.in +1c
.ti -1c
.RI "DateTime \fBDataOp\fP\fC [get, set]\fP"
.br
.RI "Propriedade para data de venda\&. "
.ti -1c
.RI "string \fBUsername\fP\fC [get, set]\fP"
.br
.RI "Propriedade para username\&. "
.ti -1c
.RI "Dictionary< int, int > \fBProds\fP\fC [get, set]\fP"
.br
.RI "Propriedade para produtos\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Created by: Diogo Created on: 29/12/2023 21:20:29\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ObjetosNegocio\&.Operacao\&.Operacao ()"

.PP
Construtor de classe por defeito\&. 
.SS "ObjetosNegocio\&.Operacao\&.Operacao (Dictionary< int, int > prods, string username, DateTime dataOp)"

.PP
Construtor de classe com os parâmetros definidos\&. 
.PP
\fBParameters\fP
.RS 4
\fIprods\fP produtos
.br
\fIusername\fP username
.br
\fIdataOp\fP data de operacao
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "abstract bool ObjetosNegocio\&.Operacao\&.EmitirFatura ()\fC [pure virtual]\fP"

.PP
Emite uma fatura\&. 
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se tudo correu bem ou não
.RE
.PP

.PP
Implemented in \fBObjetosNegocio\&.Compra\fP, and \fBObjetosNegocio\&.Venda\fP\&.
.SH "Property Documentation"
.PP 
.SS "DateTime ObjetosNegocio\&.Operacao\&.DataOp\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para data de venda\&. 
.PP
Implements \fBObjetosNegocio\&.IOperacao\fP\&.
.SS "Dictionary<int, int> ObjetosNegocio\&.Operacao\&.Prods\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para produtos\&. 
.PP
Implements \fBObjetosNegocio\&.IOperacao\fP\&.
.SS "string ObjetosNegocio\&.Operacao\&.Username\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para username\&. 
.PP
Implements \fBObjetosNegocio\&.IOperacao\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
