.TH "ObjetosNegocio.ICarrinhoCompra" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.ICarrinhoCompra \- Purpose: Created by: Diogo Created on: 20/12/2023 03:40:49\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.CarrinhoCompra\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< int, int > \fBProds\fP\fC [get, set]\fP"
.br
.RI "Propriedade de produtos\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Created by: Diogo Created on: 20/12/2023 03:40:49\&. 


.SH "Property Documentation"
.PP 
.SS "Dictionary<int, int> ObjetosNegocio\&.ICarrinhoCompra\&.Prods\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade de produtos\&. 
.PP
Implemented in \fBObjetosNegocio\&.CarrinhoCompra\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
