.TH "ObjetosNegocio.CarrinhoCompra" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.CarrinhoCompra \- Purpose: Classe de carrinho de compra Created by: Diogo Created on: 07/12/2023 21:21:00\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjetosNegocio\&.ICarrinhoCompra\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCarrinhoCompra\fP ()"
.br
.RI "Construtor de classe por defeito\&. "
.ti -1c
.RI "\fBCarrinhoCompra\fP (Dictionary< int, int > prods)"
.br
.RI "Construtor de classe com ôs parâmetros definidos\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< int, int > \fBProds\fP\fC [get, set]\fP"
.br
.RI "Propriedade de produtos\&. "
.in -1c

Properties inherited from \fBObjetosNegocio\&.ICarrinhoCompra\fP
.in +1c
.ti -1c
.RI "Dictionary< int, int > \fBProds\fP\fC [get, set]\fP"
.br
.RI "Propriedade de produtos\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Classe de carrinho de compra Created by: Diogo Created on: 07/12/2023 21:21:00\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ObjetosNegocio\&.CarrinhoCompra\&.CarrinhoCompra ()"

.PP
Construtor de classe por defeito\&. 
.SS "ObjetosNegocio\&.CarrinhoCompra\&.CarrinhoCompra (Dictionary< int, int > prods)"

.PP
Construtor de classe com ôs parâmetros definidos\&. 
.PP
\fBParameters\fP
.RS 4
\fIprods\fP produtos
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "Dictionary<int, int> ObjetosNegocio\&.CarrinhoCompra\&.Prods\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade de produtos\&. 
.PP
Implements \fBObjetosNegocio\&.ICarrinhoCompra\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
