.TH "ObjetosNegocio.IPessoa" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.IPessoa \- Purpose: Interface de pessoa Created by: Diogo Created on: 20/12/2023 03:35:05\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.Pessoa\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNome\fP\fC [get, set]\fP"
.br
.RI "Propriedade para nome\&. "
.ti -1c
.RI "DateTime \fBDataNascimento\fP\fC [get, set]\fP"
.br
.RI "Propriedade para data de nascimento\&. "
.ti -1c
.RI "\fBMorada\fP \fBLocalizacao\fP\fC [get, set]\fP"
.br
.RI "Propriedade para localizacao\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Interface de pessoa Created by: Diogo Created on: 20/12/2023 03:35:05\&. 


.SH "Property Documentation"
.PP 
.SS "DateTime ObjetosNegocio\&.IPessoa\&.DataNascimento\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para data de nascimento\&. 
.PP
Implemented in \fBObjetosNegocio\&.Pessoa\fP\&.
.SS "\fBMorada\fP ObjetosNegocio\&.IPessoa\&.Localizacao\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para localizacao\&. 
.PP
Implemented in \fBObjetosNegocio\&.Pessoa\fP\&.
.SS "string ObjetosNegocio\&.IPessoa\&.Nome\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para nome\&. 
.PP
Implemented in \fBObjetosNegocio\&.Pessoa\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
