.TH "ObjetosNegocio.IMarca" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.IMarca \- Purpose: Interface de marca Created by: Diogo Created on: 20/12/2023 03:25:35\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.Marca\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNome\fP\fC [get, set]\fP"
.br
.RI "Propriedade para nome\&. "
.ti -1c
.RI "string \fBContacto\fP\fC [get, set]\fP"
.br
.RI "Propriedade para contacto\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Interface de marca Created by: Diogo Created on: 20/12/2023 03:25:35\&. 


.SH "Property Documentation"
.PP 
.SS "string ObjetosNegocio\&.IMarca\&.Contacto\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para contacto\&. 
.PP
Implemented in \fBObjetosNegocio\&.Marca\fP\&.
.SS "string ObjetosNegocio\&.IMarca\&.Nome\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para nome\&. 
.PP
Implemented in \fBObjetosNegocio\&.Marca\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
