.TH "ObjetosNegocio.IOperacao" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.IOperacao \- Purpose: Created by: Diogo Created on: 29/12/2023 21:17:59\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.Operacao\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBDataOp\fP\fC [get, set]\fP"
.br
.RI "Propriedade para data de venda\&. "
.ti -1c
.RI "string \fBUsername\fP\fC [get, set]\fP"
.br
.RI "Propriedade para username\&. "
.ti -1c
.RI "Dictionary< int, int > \fBProds\fP\fC [get, set]\fP"
.br
.RI "Propriedade para produtos\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Created by: Diogo Created on: 29/12/2023 21:17:59\&. 


.SH "Property Documentation"
.PP 
.SS "DateTime ObjetosNegocio\&.IOperacao\&.DataOp\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para data de venda\&. 
.PP
Implemented in \fBObjetosNegocio\&.Operacao\fP\&.
.SS "Dictionary<int, int> ObjetosNegocio\&.IOperacao\&.Prods\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para produtos\&. 
.PP
Implemented in \fBObjetosNegocio\&.Operacao\fP\&.
.SS "string ObjetosNegocio\&.IOperacao\&.Username\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para username\&. 
.PP
Implemented in \fBObjetosNegocio\&.Operacao\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
