.TH "ObjetosNegocio.IFornecedor" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.IFornecedor \- Purpose: Interface de fornecedor Created by: Diogo Created on: 20/12/2023 03:32:38\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.Fornecedor\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNome\fP\fC [get, set]\fP"
.br
.RI "Propriedade para nome\&. "
.ti -1c
.RI "string \fBContacto\fP\fC [get, set]\fP"
.br
.RI "Propriedade para contacto\&. "
.ti -1c
.RI "List< \fBProduto\fP > \fBProds\fP\fC [get, set]\fP"
.br
.RI "Propriedade para produtos\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Interface de fornecedor Created by: Diogo Created on: 20/12/2023 03:32:38\&. 


.SH "Property Documentation"
.PP 
.SS "string ObjetosNegocio\&.IFornecedor\&.Contacto\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para contacto\&. 
.PP
Implemented in \fBObjetosNegocio\&.Fornecedor\fP\&.
.SS "string ObjetosNegocio\&.IFornecedor\&.Nome\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para nome\&. 
.PP
Implemented in \fBObjetosNegocio\&.Fornecedor\fP\&.
.SS "List<\fBProduto\fP> ObjetosNegocio\&.IFornecedor\&.Prods\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para produtos\&. 
.PP
Implemented in \fBObjetosNegocio\&.Fornecedor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
