.TH "ObjetosNegocio.ICategoria" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjetosNegocio.ICategoria \- Purpose: Interface de categoria Created by: Diogo Created on: 20/12/2023 03:20:54\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjetosNegocio\&.Categoria\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNome\fP\fC [get, set]\fP"
.br
.RI "Propriedade para nome\&. "
.ti -1c
.RI "string \fBDescricao\fP\fC [get, set]\fP"
.br
.RI "Propriedade para descricao\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Interface de categoria Created by: Diogo Created on: 20/12/2023 03:20:54\&. 


.SH "Property Documentation"
.PP 
.SS "string ObjetosNegocio\&.ICategoria\&.Descricao\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para descricao\&. 
.PP
Implemented in \fBObjetosNegocio\&.Categoria\fP\&.
.SS "string ObjetosNegocio\&.ICategoria\&.Nome\fC [get]\fP, \fC [set]\fP"

.PP
Propriedade para nome\&. 
.PP
Implemented in \fBObjetosNegocio\&.Categoria\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
