.TH "RegrasNegocio" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegrasNegocio
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegrasArmazem\fP"
.br
.RI "Purpose: Created by: Diogo Created on: 06/12/2023 23:16:25\&. "
.ti -1c
.RI "class \fBRegrasCompras\fP"
.br
.RI "Purpose: RegrasCompras de classe Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBRegrasFornecedores\fP"
.br
.RI "Purpose: RegrasFornecedores de classe Created by: Diogo Created on: 24/10/2023\&. "
.ti -1c
.RI "class \fBRegrasUtilizadores\fP"
.br
.RI "Purpose: Created by: Diogo Created on: 09/12/2023 00:23:58\&. "
.ti -1c
.RI "class \fBRegrasVendas\fP"
.br
.RI "Purpose: RegrasVendas de classe Created by: Diogo Created on: 24/10/2023\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
