.TH "Verificacoes.Verificacoes" 3 "Sun Dec 31 2023" "Version 3.0" "Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Verificacoes.Verificacoes \- Purpose: Created by: Diogo Created on: 06/12/2023 22:36:07\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBReferencia\fP (int refProd)"
.br
.RI "Verifica se a referência de um produto introduzida é válida\&. "
.ti -1c
.RI "static bool \fBQuantidade\fP (int quantidade)"
.br
.RI "Verifica se a quantidade de um produto que se deseja remover é válida\&. "
.ti -1c
.RI "static bool \fBEmail\fP (string email)"
.br
.RI "Verifica se um email introduzido é válido\&. "
.ti -1c
.RI "static bool \fBPassword\fP (string password)"
.br
.RI "Verifica se uma password introduzida é válida\&. "
.ti -1c
.RI "static bool \fBNome\fP (string nome)"
.br
.RI "Verifica se um nome introduzido é válido\&. "
.ti -1c
.RI "static bool \fBContacto\fP (string contacto)"
.br
.RI "Verifica se um contacto introduzido é válido\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpose: Created by: Diogo Created on: 06/12/2023 22:36:07\&. 


.SH "Member Function Documentation"
.PP 
.SS "static bool Verificacoes\&.Verificacoes\&.Contacto (string contacto)\fC [static]\fP"

.PP
Verifica se um contacto introduzido é válido\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontacto\fP contacto
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se é ou não válido
.RE
.PP

.SS "static bool Verificacoes\&.Verificacoes\&.Email (string email)\fC [static]\fP"

.PP
Verifica se um email introduzido é válido\&. 
.PP
\fBParameters\fP
.RS 4
\fIemail\fP email
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se é ou não válido
.RE
.PP

.SS "static bool Verificacoes\&.Verificacoes\&.Nome (string nome)\fC [static]\fP"

.PP
Verifica se um nome introduzido é válido\&. 
.PP
\fBParameters\fP
.RS 4
\fInome\fP nome
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se é ou não válido
.RE
.PP

.SS "static bool Verificacoes\&.Verificacoes\&.Password (string password)\fC [static]\fP"

.PP
Verifica se uma password introduzida é válida\&. 
.PP
\fBParameters\fP
.RS 4
\fIpassword\fP password
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se é ou não válido
.RE
.PP

.SS "static bool Verificacoes\&.Verificacoes\&.Quantidade (int quantidade)\fC [static]\fP"

.PP
Verifica se a quantidade de um produto que se deseja remover é válida\&. 
.PP
\fBParameters\fP
.RS 4
\fIquantidade\fP quantidade que se deseja remover
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se é ou não válido
.RE
.PP

.SS "static bool Verificacoes\&.Verificacoes\&.Referencia (int refProd)\fC [static]\fP"

.PP
Verifica se a referência de um produto introduzida é válida\&. 
.PP
\fBParameters\fP
.RS 4
\fIrefProd\fP referência de produto
.RE
.PP
\fBReturns\fP
.RS 4
true ou false, dependendo se é ou não válido
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Doxygen_Trab_Pratico_POO_LESI_Fase3_26534_26006 from the source code\&.
